// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TremorScope.Infrastructure.Storage;

#nullable disable

namespace TremorScope.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(TremorDbContext))]
    [Migration("20261002005158_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TremorScope.Infrastructure.Storage.PatientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PseudonymId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalId")
                        .IsUnique();

                    b.HasIndex("PseudonymId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("TremorScope.Infrastructure.Storage.RecordingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("AxisCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BandsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Condition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedDisplacementMm")
                        .HasColumnType("REAL");

                    b.Property<int>("MissingSamples")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PeakFrequencyHz")
                        .HasColumnType("REAL");

                    b.Property<int>("QualityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QualityMessagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Regularity")
                        .HasColumnType("REAL");

                    b.Property<double>("RmsAccelerationMg")
                        .HasColumnType("REAL");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SampleRate")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("Samples")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("TremorScope.Infrastructure.Storage.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CloudSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hand")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PacsSentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pattern")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "MeasuredAtUtc");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TremorScope.Infrastructure.Storage.RecordingEntity", b =>
                {
                    b.HasOne("TremorScope.Infrastructure.Storage.SessionEntity", "Session")
                        .WithMany("Recordings")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TremorScope.Infrastructure.Storage.SessionEntity", b =>
                {
                    b.HasOne("TremorScope.Infrastructure.Storage.PatientEntity", "Patient")
                        .WithMany("Sessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("TremorScope.Infrastructure.Storage.PatientEntity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TremorScope.Infrastructure.Storage.SessionEntity", b =>
                {
                    b.Navigation("Recordings");
                });
#pragma warning restore 612, 618
        }
    }
}
